development:
  sessions:
    default:
      database: bucketerize_dev
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: bucketerize_test
      hosts:
        - localhost:27017